services:
  server:
    build:
      context: .
      dockerfile: server/dockerfile
    environment:
      - PRINTER_CALIBRATION_BIN=/opt/printer-calibration-venv/bin/printer-calibration
      - PRINTER_CALIBRATION_PYTHON=/opt/printer-calibration-venv/bin/python
    ports:
      - "3001:3001"
    volumes:
      - server-data:/app/server/data

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    depends_on:
      - server
    ports:
      - "5173:80"

volumes:
  server-data:
    driver: local
