import { renderHook, act, waitFor } from "@testing-library/react";
import { describe, it, expect, vi, beforeEach, type Mock } from "vitest";
import { useImageProcessing } from "./useImageProcessing";
import { db } from "../db";
import { ImageProcessor } from "../helpers/imageProcessor";
import type { CardOption } from "../../../shared/types";
import { IMAGE_PROCESSING } from "../constants/imageProcessing";

// Mocks
vi.mock("../db", () => ({
  db: {
    images: {
      get: vi.fn(),
      update: vi.fn(),
      put: vi.fn(),
    },
    cardbacks: {
      get: vi.fn(),
      put: vi.fn(),
    },
    user_images: {
      get: vi.fn(),
    },
  },
}));

vi.mock("../helpers/imageProcessor");

vi.mock("../store", () => ({
  useSettingsStore: Object.assign(
    vi.fn((selector) =>
      selector({
        dpi: 300,
        darkenMode: "none",
        hasHydrated: true,
      })
    ),
    {
      persist: {
        hasHydrated: vi.fn().mockReturnValue(true),
        onFinishHydration: vi.fn().mockReturnValue(() => {}),
      },
      getState: vi.fn().mockReturnValue({
        dpi: 300,
        darkenMode: "none",
        bleedEdgeWidth: 1, // Default matching default props in tests
        unit: "mm",
      }),
    }
  ),
  useProjectStore: vi.fn((selector) =>
    selector({
      currentProjectId: "test-project-id",
    })
  ),
}));

describe("useImageProcessing", () => {
  const card: CardOption = {
    uuid: "123",
    name: "Test Card",
    order: 1,
    imageId: "image123",
    isUserUpload: false,
  };

  let mockImageProcessor: ImageProcessor;
  let mockProcess: Mock;

  beforeEach(() => {
    vi.clearAllMocks();
    mockImageProcessor = new (ImageProcessor as unknown as Mock)();
    mockProcess = mockImageProcessor.process as Mock;
  });

  it("should not process if card has no imageId", async () => {
    const { result } = renderHook(() =>
      useImageProcessing({
        unit: "mm",
        bleedEdgeWidth: 1,
        imageProcessor: mockImageProcessor,
      })
    );

    await act(async () => {
      await result.current.ensureProcessed({ ...card, imageId: undefined });
    });

    expect(db.images.get).not.toHaveBeenCalled();
    expect(mockProcess).not.toHaveBeenCalled();
  });

  it("should not process a valid cached display blob", async () => {
    (db.images.get as Mock).mockResolvedValue({
      displayBlob: new Blob(["display"]),
      displayBlobDarkened: new Blob(["darkened"]),
      exportBleedWidth: 1,
      exportDpi: 300,
      generatedHasBuiltInBleed: false,
      generatedExistingBleedMm: 0,
      generatedBleedMode: "generate",
      generatedRenderVersion: IMAGE_PROCESSING.RENDER_CACHE_VERSION,
    });
    const consoleError = vi.spyOn(console, "error");

    try {
      const { result } = renderHook(() =>
        useImageProcessing({
          unit: "mm",
          bleedEdgeWidth: 1,
          imageProcessor: mockImageProcessor,
        })
      );

      await act(async () => {
        await result.current.ensureProcessed(card);
      });

      expect(db.images.get).toHaveBeenCalledExactlyOnceWith("image123");
      expect(db.user_images.get).not.toHaveBeenCalled();
      expect(mockProcess).not.toHaveBeenCalled();
      expect(consoleError).not.toHaveBeenCalled();
    } finally {
      consoleError.mockRestore();
    }
  });

  it("should call imageProcessor.process for an unprocessed image", async () => {
    (db.images.get as Mock).mockResolvedValue({
      sourceUrl: "http://example.com/img.png",
    });
    mockProcess.mockResolvedValue({
      displayBlob: new Blob(["processed"]),
      displayDpi: 300,
      displayBleedWidth: 1,
      exportBlob: new Blob(["processed_export"]),
      exportDpi: 600,
      exportBleedWidth: 1,
      displayBlobDarkened: new Blob(["processed_darkened"]),
      exportBlobDarkened: new Blob(["processed_export_darkened"]),
    });

    const { result } = renderHook(() =>
      useImageProcessing({
        unit: "mm",
        bleedEdgeWidth: 1,
        imageProcessor: mockImageProcessor,
      })
    );

    await act(async () => {
      await result.current.ensureProcessed(card);
    });

    expect(mockProcess).toHaveBeenCalledTimes(1);
    expect(db.images.put).toHaveBeenCalled();
  });

  it("reprocesses a Zombie token blob generated by an older renderer", async () => {
    (db.images.get as Mock).mockResolvedValue({
      id: "image123",
      sourceUrl: "http://example.com/zombie.png",
      displayBlob: new Blob(["stale-display"]),
      displayBlobDarkened: new Blob(["stale-dark"]),
      exportBlob: new Blob(["stale-export"]),
      exportDpi: 300,
      exportBleedWidth: 1,
      generatedHasBuiltInBleed: false,
      generatedBleedMode: "generate",
      generatedExistingBleedMm: 0,
      generatedRenderVersion: 0,
    });
    mockProcess.mockResolvedValue({
      displayBlob: new Blob(["fresh-display"]),
      displayDpi: 300,
      displayBleedWidth: 1,
      exportBlob: new Blob(["fresh-export"]),
      exportDpi: 300,
      exportBleedWidth: 1,
      displayBlobDarkened: new Blob(["fresh-dark"]),
      exportBlobDarkened: new Blob(["fresh-export-dark"]),
    });

    const { result } = renderHook(() =>
      useImageProcessing({
        unit: "mm",
        bleedEdgeWidth: 1,
        imageProcessor: mockImageProcessor,
      })
    );

    await act(async () => {
      await result.current.ensureProcessed({
        ...card,
        name: "Zombie",
        isToken: true,
        hasBuiltInBleed: false,
      });
    });

    expect(mockProcess).toHaveBeenCalledTimes(1);
    expect(db.images.put).toHaveBeenCalledWith(
      expect.objectContaining({
        generatedRenderVersion: expect.any(Number),
      })
    );
  });

  it("should handle image processing failure", async () => {
    (db.images.get as Mock).mockResolvedValue({
      sourceUrl: "http://example.com/img.png",
    });
    const expectedError = new Error("Processing failed");
    mockProcess.mockRejectedValue(expectedError);
    const consoleError = vi.spyOn(console, "error");

    try {
      const { result } = renderHook(() =>
        useImageProcessing({
          unit: "mm",
          bleedEdgeWidth: 1,
          imageProcessor: mockImageProcessor,
        })
      );

      await act(async () => {
        await result.current.ensureProcessed(card);
      });

      // With imageId-keyed loading state, check using getLoadingState
      expect(result.current.getLoadingState(card.imageId)).toBe("error");
      expect(db.images.put).not.toHaveBeenCalled();
      expect(consoleError).toHaveBeenCalledExactlyOnceWith(
        "processCardInternal error for",
        card.name,
        expectedError
      );
    } finally {
      consoleError.mockRestore();
    }
  });

  it("reprocessSelectedImages should process multiple cards", async () => {
    const cards = [
      { ...card, uuid: "1", imageId: "img1" },
      { ...card, uuid: "2", imageId: "img2" },
    ];

    (db.images.get as Mock).mockImplementation((id) => {
      if (id === "img1")
        return Promise.resolve({ sourceUrl: "https://example.com/url1" });
      if (id === "img2")
        return Promise.resolve({ sourceUrl: "https://example.com/url2" });
      return Promise.resolve(undefined);
    });

    mockProcess.mockResolvedValue({
      displayBlob: new Blob(["processed"]),
      displayDpi: 300,
      displayBleedWidth: 1,
      exportBlob: new Blob(["processed_export"]),
      exportDpi: 600,
      exportBleedWidth: 1,
      displayBlobDarkened: new Blob(["processed_darkened"]),
      exportBlobDarkened: new Blob(["processed_export_darkened"]),
    });

    const { result } = renderHook(() =>
      useImageProcessing({
        unit: "mm",
        bleedEdgeWidth: 1,
        imageProcessor: mockImageProcessor,
      })
    );

    await act(async () => {
      await result.current.reprocessSelectedImages(cards, 2);
    });

    expect(mockProcess).toHaveBeenCalledTimes(2);
    expect(db.images.put).toHaveBeenCalledTimes(2);
  });

  it("should use originalBlob if available", async () => {
    const blob = new Blob(["test"], { type: "image/png" });
    (db.images.get as Mock).mockResolvedValue({ originalBlob: blob });
    global.URL.createObjectURL = vi.fn(() => "blob:test");
    global.URL.revokeObjectURL = vi.fn();

    mockProcess.mockResolvedValue({
      displayBlob: new Blob(["processed"]),
      displayDpi: 300,
      displayBleedWidth: 1,
      exportBlob: new Blob(["processed_export"]),
      exportDpi: 600,
      exportBleedWidth: 1,
      displayBlobDarkened: new Blob(["processed_darkened"]),
      exportBlobDarkened: new Blob(["processed_export_darkened"]),
    });

    const { result } = renderHook(() =>
      useImageProcessing({
        unit: "mm",
        bleedEdgeWidth: 1,
        imageProcessor: mockImageProcessor,
      })
    );

    await act(async () => {
      await result.current.ensureProcessed(card);
    });

    expect(global.URL.createObjectURL).toHaveBeenCalledWith(blob);
    expect(mockProcess).toHaveBeenCalledWith(
      expect.objectContaining({ url: "blob:test" }),
      expect.any(Number)
    );
    expect(global.URL.revokeObjectURL).toHaveBeenCalledWith("blob:test");
  });

  it("processes manual cardback override bleed as an inset border at layout size", async () => {
    const blob = new Blob(["cardback"], { type: "image/png" });
    const cardbackRecord = {
      id: "cardback_custom",
      originalBlob: blob,
      hasBuiltInBleed: false,
    };
    (db.cardbacks.get as Mock).mockResolvedValue(cardbackRecord);
    global.URL.createObjectURL = vi.fn(() => "blob:cardback");
    global.URL.revokeObjectURL = vi.fn();

    mockProcess.mockResolvedValue({
      displayBlob: new Blob(["processed"]),
      displayDpi: 300,
      displayBleedWidth: 1.5,
      exportBlob: new Blob(["processed_export"]),
      exportDpi: 300,
      exportBleedWidth: 1.5,
      displayBlobDarkened: new Blob(["processed_darkened"]),
      exportBlobDarkened: new Blob(["processed_export_darkened"]),
    });

    const { result } = renderHook(() =>
      useImageProcessing({
        unit: "mm",
        bleedEdgeWidth: 1.5,
        imageProcessor: mockImageProcessor,
      })
    );

    await act(async () => {
      await result.current.ensureProcessed({
        ...card,
        imageId: "cardback_custom",
        bleedMode: "generate",
        generateBleedMm: 4,
      });
    });

    expect(mockProcess).toHaveBeenCalledWith(
      expect.objectContaining({
        bleedEdgeWidth: 1.5,
        insetBorderBleedMm: 4,
        layoutBleedWidthMm: 1.5,
      }),
      expect.any(Number)
    );
    expect(db.cardbacks.put).toHaveBeenCalledWith(
      expect.objectContaining({
        id: "cardback_custom",
        exportBleedWidth: 1.5,
        generatedInsetBorderBleedMm: 4,
      })
    );
  });

  it("should handle process returning error object", async () => {
    (db.images.get as Mock).mockResolvedValue({
      sourceUrl: "http://example.com/img.png",
    });
    mockProcess.mockResolvedValue({ error: "Processing failed gracefully" });
    const consoleError = vi.spyOn(console, "error");

    try {
      const { result } = renderHook(() =>
        useImageProcessing({
          unit: "mm",
          bleedEdgeWidth: 1,
          imageProcessor: mockImageProcessor,
        })
      );

      await act(async () => {
        await result.current.ensureProcessed(card);
      });

      // With imageId-keyed loading state, check using getLoadingState
      expect(result.current.getLoadingState(card.imageId)).toBe("error");
      expect(db.images.put).not.toHaveBeenCalled();
      expect(consoleError).toHaveBeenCalledExactlyOnceWith(
        "processCardInternal error for",
        card.name,
        expect.objectContaining({ message: "Processing failed gracefully" })
      );
    } finally {
      consoleError.mockRestore();
    }
  });

  it("reprocessSelectedImages should handle errors", async () => {
    const cards = [{ ...card, uuid: "1", imageId: "img1" }];
    (db.images.get as Mock).mockResolvedValue({
      sourceUrl: "https://example.com/url1",
    });
    mockProcess.mockResolvedValue({ error: "Processing failed" });
    const consoleError = vi.spyOn(console, "error");

    try {
      const { result } = renderHook(() =>
        useImageProcessing({
          unit: "mm",
          bleedEdgeWidth: 1,
          imageProcessor: mockImageProcessor,
        })
      );

      await act(async () => {
        await result.current.reprocessSelectedImages(cards, 2);
      });

      expect(mockProcess).toHaveBeenCalledTimes(1);
      expect(db.images.put).not.toHaveBeenCalled();
      expect(consoleError).toHaveBeenCalledExactlyOnceWith(
        "processCardInternal error for",
        card.name,
        expect.objectContaining({ message: "Processing failed" })
      );
    } finally {
      consoleError.mockRestore();
    }
  });

  it("reprocessSelectedImages should submit large reprocess jobs in batches", async () => {
    const cards = Array.from({ length: 30 }, (_, i) => ({
      ...card,
      uuid: `card-${i}`,
      imageId: `img-${i}`,
    }));

    (db.images.get as Mock).mockImplementation((id) =>
      Promise.resolve({ sourceUrl: `https://example.com/${id}.png` })
    );

    let active = 0;
    let maxActive = 0;
    mockProcess.mockImplementation(() => {
      active++;
      maxActive = Math.max(maxActive, active);

      return new Promise((resolve) => {
        setTimeout(() => {
          active--;
          resolve({
            displayBlob: new Blob(["processed"]),
            displayDpi: 300,
            displayBleedWidth: 1,
            exportBlob: new Blob(["processed_export"]),
            exportDpi: 600,
            exportBleedWidth: 1,
            displayBlobDarkened: new Blob(["processed_darkened"]),
            exportBlobDarkened: new Blob(["processed_export_darkened"]),
          });
        }, 10);
      });
    });

    const { result } = renderHook(() =>
      useImageProcessing({
        unit: "mm",
        bleedEdgeWidth: 1,
        imageProcessor: mockImageProcessor,
      })
    );

    await act(async () => {
      await result.current.reprocessSelectedImages(cards, 2);
    });

    expect(mockProcess).toHaveBeenCalledTimes(30);
    expect(maxActive).toBeLessThanOrEqual(24);
  });

  describe("in-flight deduplication", () => {
    it("should NOT call process twice for same imageId requested concurrently", async () => {
      (db.images.get as Mock).mockResolvedValue({
        sourceUrl: "http://example.com/img.png",
      });

      // Make process take some time to complete
      let resolveProcess: (value: unknown) => void;
      mockProcess.mockReturnValue(
        new Promise((resolve) => {
          resolveProcess = resolve;
        })
      );

      const { result } = renderHook(() =>
        useImageProcessing({
          unit: "mm",
          bleedEdgeWidth: 1,
          imageProcessor: mockImageProcessor,
        })
      );

      // Start two requests for the same imageId concurrently
      const card1 = { ...card, uuid: "card1", imageId: "shared-image" };
      const card2 = { ...card, uuid: "card2", imageId: "shared-image" };

      let promise1Complete = false;
      let promise2Complete = false;

      await act(async () => {
        result.current.ensureProcessed(card1).then(() => {
          promise1Complete = true;
        });
        result.current.ensureProcessed(card2).then(() => {
          promise2Complete = true;
        });
      });

      // Should only call process ONCE even though two cards requested the same image
      expect(mockProcess).toHaveBeenCalledTimes(1);

      // Now resolve the process
      await act(async () => {
        resolveProcess!({
          displayBlob: new Blob(["test"]),
          displayDpi: 300,
          displayBleedWidth: 1,
          exportBlob: new Blob(["test"]),
          exportDpi: 600,
          exportBleedWidth: 1,
          displayBlobDarkened: new Blob(["test"]),
          exportBlobDarkened: new Blob(["test"]),
        });
        // Wait for promises to settle
        await new Promise((resolve) => setTimeout(resolve, 10));
      });

      // Both cards should complete
      expect(promise1Complete).toBe(true);
      expect(promise2Complete).toBe(true);
    });

    it("should skip processing for already-processed imageIds in same session", async () => {
      // First call: image needs processing
      (db.images.get as Mock).mockResolvedValue({
        sourceUrl: "http://example.com/img.png",
      });
      mockProcess.mockResolvedValue({
        displayBlob: new Blob(["test"]),
        displayDpi: 300,
        displayBleedWidth: 1,
        exportBlob: new Blob(["test"]),
        exportDpi: 600,
        exportBleedWidth: 1,
        displayBlobDarkened: new Blob(["test"]),
        exportBlobDarkened: new Blob(["test"]),
      });

      const { result } = renderHook(() =>
        useImageProcessing({
          unit: "mm",
          bleedEdgeWidth: 1,
          imageProcessor: mockImageProcessor,
        })
      );

      await act(async () => {
        await result.current.ensureProcessed(card);
      });

      expect(mockProcess).toHaveBeenCalledTimes(1);
      mockProcess.mockClear();

      // Second call with different card but same imageId
      // Mock should return generatedHasBuiltInBleed to indicate settings are not invalidated
      (db.images.get as Mock).mockResolvedValue({
        sourceUrl: "http://example.com/img.png",
        exportDpi: 300,
        exportBleedWidth: 1,
        generatedHasBuiltInBleed: false, // Settings not invalidated
        generatedBleedMode: "generate",
        generatedExistingBleedMm: 0,
        generatedRenderVersion: IMAGE_PROCESSING.RENDER_CACHE_VERSION,
      });
      const card2 = { ...card, uuid: "different-uuid", imageId: "image123" };

      await act(async () => {
        await result.current.ensureProcessed(card2);
      });

      // Should NOT call process again - already processed in this session
      expect(mockProcess).not.toHaveBeenCalled();
    });
  });

  describe("getLoadingState", () => {
    it("should return 'idle' for undefined imageId", () => {
      const { result } = renderHook(() =>
        useImageProcessing({
          unit: "mm",
          bleedEdgeWidth: 1,
          imageProcessor: mockImageProcessor,
        })
      );

      expect(result.current.getLoadingState(undefined)).toBe("idle");
    });

    it("should return 'idle' for unknown imageId", () => {
      const { result } = renderHook(() =>
        useImageProcessing({
          unit: "mm",
          bleedEdgeWidth: 1,
          imageProcessor: mockImageProcessor,
        })
      );

      expect(result.current.getLoadingState("unknown-image")).toBe("idle");
    });

    it("should return 'loading' while processing", async () => {
      (db.images.get as Mock).mockResolvedValue({
        sourceUrl: "http://example.com/img.png",
      });

      let resolveProcess: (value: unknown) => void;
      mockProcess.mockReturnValue(
        new Promise((resolve) => {
          resolveProcess = resolve;
        })
      );

      const { result } = renderHook(() =>
        useImageProcessing({
          unit: "mm",
          bleedEdgeWidth: 1,
          imageProcessor: mockImageProcessor,
        })
      );

      // Start processing (don't await)
      act(() => {
        result.current.ensureProcessed(card);
      });

      // Give time for state update
      await act(async () => {
        await new Promise((resolve) => setTimeout(resolve, 10));
      });

      // Should be loading
      expect(result.current.getLoadingState(card.imageId)).toBe("loading");

      // Complete processing
      await act(async () => {
        resolveProcess!({
          displayBlob: new Blob(["test"]),
          displayDpi: 300,
          displayBleedWidth: 1,
          exportBlob: new Blob(["test"]),
          exportDpi: 600,
          exportBleedWidth: 1,
          displayBlobDarkened: new Blob(["test"]),
          exportBlobDarkened: new Blob(["test"]),
        });
        await new Promise((resolve) => setTimeout(resolve, 10));
      });

      // Should be idle after completion
      expect(result.current.getLoadingState(card.imageId)).toBe("idle");
    });
  });

  it("revokes only its owned blob URL after an active worker is cancelled following unmount", async () => {
    const ownedUrl = "blob:hook-owned";
    const createObjectURL = vi.fn(() => ownedUrl);
    const revokeObjectURL = vi.fn();
    const originalCreateObjectURL = URL.createObjectURL;
    const originalRevokeObjectURL = URL.revokeObjectURL;
    const workers: Array<{
      postMessage: ReturnType<typeof vi.fn>;
      terminate: ReturnType<typeof vi.fn>;
      onmessage: ((event: MessageEvent) => void) | null;
      onerror: ((event: ErrorEvent) => void) | null;
    }> = [];

    class ActiveWorker {
      postMessage = vi.fn();
      terminate = vi.fn();
      onmessage: ((event: MessageEvent) => void) | null = null;
      onerror: ((event: ErrorEvent) => void) | null = null;

      constructor() {
        workers.push(this);
      }
    }

    URL.createObjectURL = createObjectURL;
    URL.revokeObjectURL = revokeObjectURL;
    vi.stubGlobal("Worker", ActiveWorker);

    const { ImageProcessor: RealImageProcessor } = await vi.importActual<
      typeof import("../helpers/imageProcessor")
    >("../helpers/imageProcessor");
    const pool = RealImageProcessor.getInstance();

    try {
      const blob = new Blob(["original"], { type: "image/png" });
      (db.images.get as Mock).mockResolvedValue({ originalBlob: blob });
      const { result, unmount } = renderHook(() =>
        useImageProcessing({
          unit: "mm",
          bleedEdgeWidth: 1,
          imageProcessor: pool as unknown as ImageProcessor,
        })
      );

      const cancelProcessing = result.current.cancelProcessing;
      let processing: Promise<void>;
      await act(async () => {
        processing = result.current.ensureProcessed(card);
        await Promise.resolve();
      });

      await waitFor(() => {
        expect(workers).toHaveLength(1);
        expect(workers[0].postMessage).toHaveBeenCalledTimes(1);
      });
      expect(createObjectURL).toHaveBeenCalledExactlyOnceWith(blob);

      unmount();
      expect(revokeObjectURL).not.toHaveBeenCalled();

      await act(async () => {
        cancelProcessing();
        await processing!;
      });

      expect(workers[0].terminate).toHaveBeenCalledTimes(1);
      expect(revokeObjectURL.mock.calls).toEqual([[ownedUrl]]);
    } finally {
      pool.destroy();
      URL.createObjectURL = originalCreateObjectURL;
      URL.revokeObjectURL = originalRevokeObjectURL;
      vi.unstubAllGlobals();
    }
  });
});
